water_control/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('watering.urls')),
    # url(r'^watering/', include('watering.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

watering/urls.py
from django.conf.urls import patterns, url
from watering.views.temp_view import TempDeviceDetail
from watering.views.watering_view import WateringMain, BranchDetail, CommandView, BranchUpdate

urlpatterns = patterns('',
                       url(r'^$', WateringMain.as_view(), name='main'),
                       url(r'/maintanence^$', WateringMain.as_view(), name='main'),
                       url(r'^branch/(?P<pk>\d+)/$', BranchDetail.as_view(), name='branch-detail'),
                       url(r'^branch/(?P<pk>\d+)/save$', BranchUpdate.as_view(), name='branch-upd'),
                       url(r'^branch/(?P<pk>\d+)/(?P<cmd>\w+)$', CommandView.as_view(), name='branch-cmd'),
                       url(r'^temp/(?P<pk>\d+)/$', TempDeviceDetail.as_view(), name='temp-detail'),
                       url(r'^temp/(?P<pk>\d+)/save$', TempDeviceDetail.as_view(), name='temp-upd'),
)

watering/models.py
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.

class Device(models.Model):
    name = models.CharField(max_length=15)
    descr = models.CharField(max_length=30)
    value = models.CharField(max_length=7, default='N/A')

    def __str__(self):
        return self.descr

    def get_absolute_url(self):
        return reverse('temp-detail', kwargs={'pk': self.pk})


# todo: Creation of default values for statuses
class Status(models.Model):
    name = models.CharField(max_length=15)
    descr = models.CharField(max_length=30)

    def __str__(self):
        return self.descr


class Branch(models.Model):
    leg = models.IntegerField(default=-1, max_length=2)
    descr = models.CharField(max_length=30)
    status = models.ForeignKey(Status)
    t_start_plan = models.TimeField(null=True, blank=True)
    t_start_fact = models.TimeField(null=True, blank=True)
    # equals t_start + duration and must be set when start and be clean up when finish
    t_end_plan = models.TimeField(null=True, blank=True)
    # must be set when real stop occurs
    t_end_fact = models.TimeField(null=True, blank=True)

    # in minutes
    duration = models.IntegerField(default=30)

    monday = models.BooleanField(default=False)
    tuesday = models.BooleanField(default=False)
    wednesday = models.BooleanField(default=False)
    thursday = models.BooleanField(default=False)
    friday = models.BooleanField(default=False)
    saturday = models.BooleanField(default=False)
    sunday = models.BooleanField(default=False)

    last_accessed = models.DateTimeField(null=True)

    def __str__(self):
        return self.descr

    def get_absolute_url(self):
        return reverse('branch-detail', kwargs={'pk': self.pk})


class Maintanence(models.Model):
    name = models.CharField(max_length=30)


class Maintanence_log(models.Model):
    maintanence = models.ForeignKey(Maintanence)
    work_description = models.CharField(max_length=50)
    last_accessed = models.DateTimeField()

watering/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader, Context
from models import Branch
from temp_mon import *
# Create your views here.

def index1(request):
    return HttpResponse("Test")


def index(request):
    t = loader.get_template('watering/base_watering.html')

    temperatures = read_temp()
    devices = get_devices()
    dd = []
    for dev, temp in devices.iteritems():
        dd.append({'device': dev, 'temp': temp})
    branches = Branch.objects.all()
    c = Context({
        'title': 'This is my app. It uses Django templates',
        'result': branches,
        'temp_result': dd,
    })
    return HttpResponse(t.render(c))

watering/views/temp_view.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, FormView, UpdateView
from watering.models import Device

__author__ = 'bonecrusher'


# Получение детального представления датчика\устройства
class TempDeviceDetail(DetailView, UpdateView):

    model = Device
    # name of context variable which we use in template
    context_object_name = 'device'
    # name of template where details are displayed
    template_name = "watering/base_watering_tempdevice_details.html"
    # fields which we will change\edit
    fields = ['descr']

    # where we should be redirected after success operation
    success_url = reverse_lazy('main')

    def get_object(self):
        object = super(TempDeviceDetail, self).get_object()
        object.last_accessed = timezone.now()
        object.save()
        return object

watering/views/watering_view.py
# -*- coding: utf-8 -*-
from django import forms
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views.generic import TemplateView, DetailView, RedirectView, FormView, UpdateView
from core_scripts.cmd_client import CommandSender
from core_scripts.command import Command, CommandInner
from core_scripts.job_manager import JobManager
from ..models import Branch, Status, Device
from ..temp_mon import *
from datetime import datetime, date
from django.shortcuts import render
from watering.models import Maintanence_log, Maintanence


__author__ = 'bonecrusher'


# Главная страница
class WateringMain(TemplateView):
    template_name = "watering/base_watering.html"

    def get_time(self, str_time):
        try:
            res_time = datetime.strptime(str_time, "%H:%M").time()
        except:
            str_time = str_time.replace(".", "")
            res_time = datetime.strptime(str_time, "%I:%M %p").time()
        return res_time

    # Сохранение данных с главной страницы
    def post(self, request):
        post_data = request.POST
        key = "maintanence_inp"

        # получаем обсулживаемый элемент из БД
        if post_data.has_key(key):
            value = post_data[key]
            if len(value):
                m_list = list(Maintanence.objects.filter(name=value))
                if not m_list or len(m_list) <= 0:
                    m = Maintanence(name=post_data[key])
                    m.save()
                else:
                    m = m_list[0]

                # что делали
                key = "maintanence_work_inp"
                if post_data.has_key(key):
                    work_descr = post_data[key]

                # пишем в базу
                ml = Maintanence_log(maintanence=m, work_description=work_descr, last_accessed=datetime.now())
                ml.save()
        else:
            branches = Branch.objects.all()
            for b in branches:
                b_id = str(b.id)
                key = 't_start_plan_' + b_id
                if post_data.has_key(key):
                    t_start = post_data[key]

                key = 't_end_plan_' + b_id
                if post_data.has_key(key):
                    t_end = post_data[key]

                key = 'length_' + b_id
                if post_data.has_key(key):
                    len_from_form = post_data[key]

                b.t_start_plan = self.get_time(t_start)
                b.t_end_plan = self.get_time(t_end)
                delta = datetime.combine(date.today(), b.t_end_plan) - datetime.combine(date.today(), b.t_start_plan)
                l = delta.seconds / 60
                b.duration = l

                day = 'monday_' + b_id
                if post_data.has_key(day):
                    b.monday = True
                else:
                    b.monday = False

                day = 'tuesday_' + b_id
                if post_data.has_key(day):
                    b.tuesday = True
                else:
                    b.tuesday = False
                day = 'wednesday_' + b_id
                if post_data.has_key(day):
                    b.wednesday = True
                else:
                    b.wednesday = False
                day = 'thursday_' + b_id
                if post_data.has_key(day):
                    b.thursday = True
                else:
                    b.thursday = False
                day = 'friday_' + b_id
                if post_data.has_key(day):
                    b.friday = True
                else:
                    b.friday = False
                day = 'saturday_' + b_id
                if post_data.has_key(day):
                    b.saturday = True
                else:
                    b.saturday = False
                day = 'sunday_' + b_id
                if post_data.has_key(day):
                    b.sunday = True
                else:
                    b.sunday = False
                b.save()

        return render(request, self.template_name, self.get_context_data())


    def get_context_data(self, **kwargs):
        context = super(WateringMain, self).get_context_data(**kwargs)

        temperatures = read_temp()
        temp_dev_list = list(Device.objects.all())
        # Инициализация. Если в базе нет устройств
        if len(temp_dev_list) == 0:
            # то получем список подсоединенных устройств и пишем его в базу
            devices = get_devices()
            for d in devices:
                new_device = Device(name=d, descr=d)
                new_device.save()
            temp_dev_list = list(Device.objects.all())
        dd = []
        devices = get_devices()
        for dev, temp in devices.iteritems():
            dd.append({'device': dev, 'temp': temp})
            td = next(temp_dev for temp_dev in temp_dev_list if temp_dev.name == dev)
            if td:
                td.value = temp

        # Читаем полив
        branches = Branch.objects.all()

        # todo: last events for 3 month for example...
        maintanence_log = list(Maintanence_log.objects.all().order_by('-last_accessed'))
        maintanence = Maintanence.objects.all()

        context['title'] = 'This is my app. It uses Django templates'
        context['result'] = branches
        context['temp_result'] = temp_dev_list
        context['maintanence'] = maintanence
        context['maintanence_log'] = maintanence_log

        return context


# Получение детального представления ветки
class BranchDetail(DetailView):
    model = Branch
    context_object_name = 'branch'
    template_name = "watering/base_watering_branch_details.html"


    def get_object(self):
        object = super(BranchDetail, self).get_object()
        last_accessed = object.last_accessed
        object.last_accessed = timezone.now()
        object.save()
        # Показываем предыдущее значение
        object.last_accessed = last_accessed
        return object


class BranchUpdate(RedirectView):
    pattern_name = 'main'
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        # ищем ветку
        branch = get_object_or_404(Branch, pk=kwargs['pk'])
        start_plan = self.request.POST['t_start_plan']
        try:
            branch.t_start_plan = datetime.strptime(start_plan, "%H:%M").time()
            branch.save()
        except:
            start_plan = start_plan.replace(".", "")
            branch.t_start_plan = datetime.strptime(start_plan, "%I:%M %p").time()
            branch.save()

        return reverse(self.pattern_name)


# Команды для ветки
class CommandView(RedirectView):
    pattern_name = 'main'
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        # ищем ветку
        branch = get_object_or_404(Branch, pk=kwargs['pk'])
        # по команде ищем статус из БД
        cmd = kwargs['cmd']
        stat = None

        if cmd == 'start':
            stat = Status.objects.get(name=JobManager.STATUS_PLANNED)
        elif cmd == 'stop':
            stat = Status.objects.get(name=JobManager.STATUS_STOPPED)
        elif cmd == 'on':
            stat = Status.objects.get(name=JobManager.STATUS_RUNNING)
            CommandSender.send(CommandInner(Command.CMD_SET, branch.leg))
        elif cmd == 'off':
            stat = Status.objects.get(name=JobManager.STATUS_STOPPED)
            CommandSender.send(CommandInner(Command.CMD_UNSET, branch.leg))

        if stat:
            branch.status = stat
            branch.save()
        return reverse(self.pattern_name)

templates/watering/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}My amazing site{% endblock %}</title>

    {% load staticfiles %}
    <link href="{% static "jquery-ui.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "jquery-clockpicker.css" %}" rel="stylesheet" type="text/css">
    <script src="{{ STATIC_URL }}jquery-1.11.1.js"></script>
    <script src="{% static "jquery-ui.js" %}"></script>
    <script src="{% static "jquery-clockpicker.js" %}"></script>
    <script src="{% static "jquery.dataTables.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "style.css" %}" type="text/css"/>
    <link rel="stylesheet" href="{% static "jquery.dataTables.css" %}" type="text/css"/>

    {% block code %}
    {% endblock code %}
</head>
<body>
<div id="wrap">
    <div id="header"><h1> {% block header %} Document Heading {% endblock %} </h1></div>
    <div id="nav">
        <ul>
            <li><a href="{% url "main" %}">Main page</a></li>
        </ul>
    </div>
    <div id="main">
        {% block main %}
            <h2>Column 1</h2>

            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit...</p>
        {% endblock %}
    </div>
    <div id="sidebar">
        {% block sidebar %}
            <h2>Column 2</h2>

            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit...</p>
            <ul>
                <li><a href="#">Link 1</a></li>
                <li><a href="#">Link 2</a></li>
                ...
            </ul>
        {% endblock %}
    </div>
    <div id="footer">
        {% block footer %}
            <p>Footer</p>
        {% endblock %}
    </div>
</div>
</body>
</html>

templates/watering/base_watering.html
{% extends "watering/base.html" %}
{% block code %}
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load("visualization", "1", {packages: ["timeline"]});
        google.setOnLoadCallback(drawChart);

        function drawChart() {
            var container = document.getElementById('timeline');
            var chart = new google.visualization.Timeline(container);
            var dataTable = new google.visualization.DataTable();

            dataTable.addColumn({type: 'string', id: 'Branch'});
            dataTable.addColumn({type: 'date', id: 'Start'});
            dataTable.addColumn({type: 'date', id: 'End'});
            dataTable.addRows([
                {% for branch in result %}
                    {% if branch.t_end_plan %}
                        ['{{ branch.descr }}', new Date(0, 0, 0, {{ branch.t_start_plan|date:"H,i,0"  }}), new Date(0, 0, 0, {{ branch.t_end_plan|date:"H,i,0"  }})],
                    {% endif %}
                    {% comment %}['Washington', new Date(1789, 3, 29), new Date(1797, 2, 3)],
                    ['Adams', new Date(1797, 2, 3), new Date(1801, 2, 3)],
                    ['Jefferson', new Date(1801, 2, 3), new Date(1809, 2, 3)]]);{% endcomment %}
                {% endfor %}
            ]);
            chart.draw(dataTable);
        }
    </script>
    {% comment %} {id: {{ session.id }}, group: {{ session.user.id }},
content: '<div class="mystyle"
               title="c {{ session.sbegin|date:"H:i:s" }} по {{ session.send|date:"H:i:s" }}">{{ session.sduration }} мин.</div>',
start: '{{ session.sbegin|date:"Y-m-d H:i:s" }}',
end: '{{ session.send|date:"Y-m-d H:i:s" }}',
type: 'range', cdata: '{{ session.comment }}',
from: '{{ session.sbegin|date:"H:i:s" }}',
to: '{{ session.send|date:"H:i:s" }}'}
  {% endcomment %}
    <script type="text/javascript">
        $(function () {
            $("input[type=submit], input[type=button]")
                    .button()
                    .click(function (event) {
                        event.default
                    });
            $("div.format").buttonset();
        });


        $(document).ready(function () {

            $("input[type='button'][id*='cmd']").click(function () {
                var id = $(this).attr("id").substring($(this).attr("id").lastIndexOf("_") + 1);
                var c = $(this).attr("name");
                {% comment %} $.ajax({
                     url: "branch/" + id + "/" + c,
                     type: "GET"
                 });{% endcomment %}
                window.location.href = "branch/" + id + "/" + c;
                return true;
            });
            {# Disable/Enable buttons due to current Branch status #}
            $("input[type='button'][id*='cmd']").each(function (index) {
                var id = $(this).attr("id").substring($(this).attr("id").lastIndexOf("_") + 1);
                var selector = '#stat_' + id
                var stat = $(selector).val()
                var start = $('#cmd_start_' + id)
                var stop = $('#cmd_stop_' + id)

                if ((stat == 'run') || (stat == 'plan')) {
                    start.prop('disabled', true);
                    stop.prop('disabled', false);
                } else if ((stat == 'stop') || (stat == 'not init')) {
                    start.prop('disabled', false);
                    stop.prop('disabled', true);
                }
            });


            $('#maintanence_tbl').DataTable();

        });
    </script>
    <style>
        #format, #ctr_btns, #maint_save {
            font-size: 0.8em
        }


    </style>
{% endblock %}
{% block header %} {{ title }} {% endblock %}
{% block main %}
    <form method="POST" action="" id="branch_form">
        {% csrf_token %}
        <table>
            <thead>
            <tr align="left">
                <th>№</th>
                <th>Полив</th>
                <th>State</th>
                <th>Start</th>
                <th>Stop</th>
                <th>Controls</th>
            </tr>
            </thead>
            <tbody>
            {% for branch in result %}
                <tr>
                    <td><span class="ui-widget ui-state-default ui-button-text"
                              style="background: none; color: #000000; border: none">{{ forloop.counter }}</span></td>
                    <td>
                        <table>
                            {# Дни недели #}
                            <tr>
                                <td><a href="{{ MEDIA_URL }}branch/{{ branch.id }}">{{ branch.descr }}</a>

                                    <div id="format" class="format">
                                        <input type="checkbox" id="id_monday_{{ branch.id }}"
                                               name="monday_{{ branch.id }}"
                                               {% if branch.monday == True %}checked="{{ branch.monday }}" {% endif %}/>
                                        <label for="id_monday_{{ branch.id }}">Mn</label>
                                        <input type="checkbox" id="id_tuesday_{{ branch.id }}"
                                               name="tuesday_{{ branch.id }}"
                                               {% if branch.tuesday == True %}checked="{{ branch.tuesday }}"{% endif %}/>
                                        <label for="id_tuesday_{{ branch.id }}">Tu</label>
                                        <input type="checkbox" id="id_wednesday_{{ branch.id }}"
                                               name="wednesday_{{ branch.id }}"
                                               {% if branch.wednesday == True %}checked="{{ branch.wednesday }}"{% endif %}/>
                                        <label for="id_wednesday_{{ branch.id }}">Wd</label>
                                        <input type="checkbox" id="id_thursday_{{ branch.id }}"
                                               name="thursday_{{ branch.id }}"
                                               {% if branch.thursday == True %}checked="{{ branch.thursday }}"{% endif %}/>
                                        <label for="id_thursday_{{ branch.id }}">Th</label>
                                        <input type="checkbox" id="id_friday_{{ branch.id }}"
                                               name="friday_{{ branch.id }}"
                                               {% if branch.friday == True %}checked="{{ branch.friday }}"{% endif %}/>
                                        <label for="id_friday_{{ branch.id }}">Fr</label>
                                        <input type="checkbox" id="id_saturday_{{ branch.id }}"
                                               name="saturday_{{ branch.id }}"
                                                {% if branch.saturday == True %}
                                               checked="{{ branch.saturday }}"{% endif %}/>
                                        <label for="id_saturday_{{ branch.id }}">St</label>
                                        <input type="checkbox" id="id_sunday_{{ branch.id }}"
                                               name="sunday_{{ branch.id }}"
                                               {% if branch.sunday == True %}checked="{{ branch.sunday }}"{% endif %}/>
                                        <label for="id_sunday_{{ branch.id }}">Su</label>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </td>
                    <td>
                        {% with status=branch.status.descr %}
                            {% if status == "Stopped" %}
                                <img src="{{ STATIC_URL }}/images/stop1normal.png" width="35px" height="35px"/>
                            {% elif status == "Running" %}
                                <img src="{{ STATIC_URL }}/images/run.png" width="35px" height="35px"/>
                            {% elif status == "Planned" %}
                                <img src="{{ STATIC_URL }}/images/stepforwardnormal.png" width="35px" height="35px"/>
                            {% elif status == "Not initialized" %}
                                <img src="{{ STATIC_URL }}/images/close.png" width="35px" height="35px"/>
                            {% endif %}
                        {% endwith %}
                    </td>
                    <td>
                        <div class="input-group clockpicker" data-autoclose="true" data-placement="left"
                             data-align="top">
                            <input id="id_t_start_plan_{{ branch.id }}" name="t_start_plan_{{ branch.id }}"
                                   value="{{ branch.t_start_plan |date:"H:i" }}"
                                   size="5">
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-time"></span>
                                            </span>
                        </div>
                    </td>
                    <td>
                        <div class="input-group clockpicker" data-autoclose="true" data-placement="left"
                             data-align="top">
                            <input id="id_t_end_plan_{{ branch.id }}" name="t_end_plan_{{ branch.id }}"
                                   value="{{ branch.t_end_plan |date:"H:i" }}"
                                   size="5">
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-time"></span>
                                            </span>
                        </div>
                    </td>
                    <td class="tableHead">
                        <div id="ctr_btns">
                            <input type="hidden" value="{{ branch.status.name }}" id="stat_{{ branch.id }}"/>
                            <input type="text" value="{{ branch.duration | default:'0' }}" name="length_{{ branch.id }}"
                                   id="len_{{ branch.id }}" size="2"/>
                            <input type="button" name="start" id="cmd_start_{{ branch.id }}" value="Start"/>
                            {#                    <div class="btn_blue" name="start" id="cmd_start_{{ branch.id }}">Start</div>#}
                            <input type="button" name="stop" id="cmd_stop_{{ branch.id }}" value="Stop"/>
                            {#                    <div class="btn_red" name="stop" id="cmd_stop_{{ branch.id }}">Stop</div>#}
                            <input type="button" name="on" id="cmd_on_{{ branch.id }}" value="On"/>
                            <input type="button" name="off" id="cmd_off_{{ branch.id }}" value="Off"/>
                        </div>
                    </td>
                </tr>

            {% endfor %}
            <tr>
                <td colspan="6" align="right">
                    <input type="submit" value="Save">
                </td>
            </tr>
            </tbody>
        </table>

    </form>
    {#    <div id="timeline" style="width: 620px; height: 380px;"></div>#}
{% endblock %}
{% block sidebar %}
    <h2>Инфо</h2>{% now "H:i j\.n\.Y" %}
    <p></p>
    {% if temp_result %}
        <table>
            <thead>
            <tr>
                <th>Датчик</th>
                <th>°C</th>
            </tr>
            </thead>
            <tbody>

            {% for temp in temp_result %}
                <tr>
                    <td><a href="{{ MEDIA_URL }}temp/{{ temp.id }}">{{ temp.descr }}</a></td>
                    <td>{{ temp.value }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h3>No data from temperature sensors</h3>
        <br/>
        <br/>
        <br/>
        <br/>
    {% endif %}
    <h2>События</h2>
    <p></p>

    <form method="POST" action="" id="maint_form">
        {% csrf_token %}
        <table>
            <tr>
                <td>
                    <label for="maintanence_inp">Обслуживался:</label>
                </td>
                <td>
                    <input list="maintanence_dl_id" name="maintanence_inp" id="maintanence_inp">
                    <datalist id="maintanence_dl_id" name="maintanence_dl_name">
                        {% for m in maintanence %}
                            <option value="{{ m.name }}">
                        {% endfor %}
                    </datalist>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="maintanence_inp">Работы:</label>
                </td>
                <td>
                    <input list="maintanence_work_dl_id" name="maintanence_work_inp" id="maintanence_work_inp"
                           value="Замена">
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" id="maint_save" value="Save"/>
                </td>
            </tr>
        </table>
    </form>
    <br/>
    <br/>
    <table id="maintanence_tbl" class="display" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Что</th>
            <th>Как</th>
            <th>Когда</th>
        </tr>
        </thead>
        <tbody>
        {% for ml in maintanence_log %}
            <tr>
                <td>{{ ml.maintanence.name }}</td>
                <td>{{ ml.work_description }}</td>
                <td>{{ ml.last_accessed|date:"H:i" }} {{ ml.last_accessed|date:"j\.n\.Y" }} </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}
{% block footer %}
    <script type="text/javascript">
        $('.clockpicker').clockpicker();
    </script>
{% endblock %}

templates/watering/base_watering_branch_details.html
{% extends "watering/base_watering.html" %}
{% block code %}

{% endblock %}
{% block header %}
    This is my app. It uses Django templates
{% endblock %}
{% block main %}
    <form class="cmxform" action="save" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>{{ branch.descr }}</legend>
            <ol>
                <li>
                    <label for="id_status">Status</label>
                    <input id="id_status" type="text" value="{{ branch.status }}" readonly="true"/>
                </li>
                <li>
                    <label for="id_descr">Description</label>
                    <input id="id_descr" name="descr" value="{{ branch.descr }}" type="text"/>
                </li>
                <li>
                    <label for="id_last_accessed">Last accessed</label>
                    <input id="id_last_accessed" value="{{ branch.last_accessed }}"/>
                </li>
                <li>
                    <label for="id_t_start">Planned s_time</label>

                    <div class="input-group clockpicker" data-autoclose="true" data-placement="left" data-align="top">
                        <input id="id_t_start_plan" name="t_start_plan" value="{{ branch.t_start_plan }}"
                               class="form-control">
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-time"></span>
                                            </span>
                    </div>
                    {#                    <input id="id_t_start2" value="00:00:01" type="text"/>#}
                </li>
                <li>
                    <label for="id_duration">Duration,min</label>
                    <input id="id_duration" name='duration' value="{{ branch.duration }}" type="text"/>
                </li>
            </ol>
        </fieldset>
        <input type="submit" value="Submit"/>
    </form>
    <script type="text/javascript">
        $('.clockpicker').clockpicker();
        $('.clockpicker').clockpicker()
                .find('input').change(function () {
{#                    $('#id_t_start2').val(this.value)#}
{#                    $('#id_t_start2').value(this.value)#}
                });
    </script>
{% endblock %}

templates/watering/base_watering_tempdevice_details.html
{% extends "watering/base_watering.html" %}
{% block header %}
    This is my app. It uses Django templates
{% endblock %}
{% block main %}
    <form class="cmxform" action="save" method="post">
    {% csrf_token %}
        <fieldset>
            <legend>{{ device.descr }}</legend>
            <ol>
                <li>
                    <label for="id_name">Name<em>*</em></label>
                    <input id="id_name" name="name" type="text" value="{{ device.name }}" readonly="true"/>
                </li>
                <li>
                    <label for="id_descr">Description</label>
                    <input id="id_descr" name="descr" value="{{ device.descr }}" type="text"/>
                </li>
                <li>
                    <label for="last_accessed">Last accessed</label>
                    <input id="last_accessed" value="{{ device.last_accessed }}"/>
                </li>
            </ol>
        </fieldset>
        <input type="submit" value="Save"/>
        <input type="reset" value="Reset"/>
    </form>
{% endblock %}